name: Linting Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js with version 18
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies (including stylelint)
      - name: Install dependencies
        run: |
          npm install

      # Run stylelint on CSS files
      - name: Run Stylelint
        run: |
          npx stylelint '**/*.css'

      # Optionally: Run HTMLHint for HTML files
      - name: Run HTMLHint
        run: |
          npx htmlhint '**/*.html'
